// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FyPepzUd-1WMwuGzOCv3-X_rW88DHA4',
    appId: '1:875343869249:android:7feb810199ad79811e1dc0',
    messagingSenderId: '875343869249',
    projectId: 'chatbox-c12c8',
    databaseURL:
        'https://chatbox-c12c8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatbox-c12c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLP7iX4KiE9WbsySSgFhM68p1R_Q5fRW8',
    appId: '1:875343869249:ios:4367b64be0e6d0781e1dc0',
    messagingSenderId: '875343869249',
    projectId: 'chatbox-c12c8',
    databaseURL:
        'https://chatbox-c12c8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatbox-c12c8.appspot.com',
    iosClientId:
        '875343869249-lpvb1a48qdjge1c3edq3g5hivl46v5s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );
}
